add better error handling

diff --git a/cliwrap b/cliwrap
--- a/cliwrap
+++ b/cliwrap
@@ -4,11 +4,16 @@
 # This file is protected under the MIT License.
 # Please see the LICENSE and the README file for more information.
 
+# Would you like to contribute?
+# Head on to our Github repository:
+# https://github.com/islemci/cliwrap
+
 # Set colors for terminal output
 CYAN='\033[0;36m'
 MAGENTA='\033[0;35m'
 GREEN='\033[0;32m'
 YELLOW='\033[1;33m'
+RED='\033[0;31m'
 RESET='\033[0m'
 
 # Function to detect the history file based on the flag
@@ -17,22 +22,22 @@ detect_history_file() {
         if [[ -f "$HOME/.zsh_history" ]]; then
             echo "$HOME/.zsh_history"
         else
-            echo "Error: Zsh history file not found at $HOME/.zsh_history" >&2
-            exit 1
+            echo -e "${RED}The specified terminal history file was not found! Why don't you run \`cliwrap -h\` to find a compatible one?${RESET}" >&2
+            return 1
         fi
     elif [[ "$1" == "-bash" ]]; then
         if [[ -f "$HOME/.bash_history" ]]; then
             echo "$HOME/.bash_history"
         else
-            echo "Error: Bash history file not found at $HOME/.bash_history" >&2
-            exit 1
+            echo -e "${RED}The specified terminal history file was not found! Why don't you run \`cliwrap -h\` to find a compatible one?${RESET}" >&2
+            return 1
         fi
     elif [[ "$1" == "-csh" ]] || [[ "$1" == "-tcsh" ]]; then
         if [[ -f "$HOME/.history" ]]; then
             echo "$HOME/.history"
         else
-            echo "Error: Csh/Tcsh history file not found at $HOME/.history" >&2
-            exit 1
+            echo -e "${RED}The specified terminal history file was not found! Why don't you run \`cliwrap -h\` to find a compatible one?${RESET}" >&2
+            return 1
         fi
     else
         if [[ -f "$HOME/.zsh_history" ]]; then
@@ -42,8 +47,8 @@ detect_history_file() {
         elif [[ -f "$HOME/.history" ]]; then
             echo "$HOME/.history"
         else
-            echo "Error: No history file found" >&2
-            exit 1
+            echo -e "${RED}We couldn't find a compatible history file! Why don't you run \`cliwrap -h\` to find a compatible one?${RESET}" >&2
+            return 1
         fi
     fi
 }
@@ -55,7 +60,7 @@ preprocess_history() {
         cat "$file" | LC_ALL=C tr -cd '\11\12\15\40-\176' # Allow printable ASCII characters only
     else
         echo "Error: No history file found" >&2
-        exit 1
+        return 1
     fi
 }
 
@@ -123,6 +128,9 @@ main() {
 
     local history_file
     history_file=$(detect_history_file "$1")
+    if [[ $? -ne 0 ]]; then
+        exit 1
+    fi
 
     display_title
 
@@ -131,6 +139,9 @@ main() {
     # Preprocess history file to remove problematic characters
     local history_data
     history_data=$(preprocess_history "$history_file")
+    if [[ $? -ne 0 ]]; then
+        exit 1
+    fi
 
     # Top tools
     local top_tools
@@ -149,5 +160,3 @@ main() {
 }
 
 main "$@"
-
-# Made by musti <3 @islemci on Github.
